org: rjlopez
app: polenmad
service: polenmad

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-3

plugins:
  - serverless-offline
  - serverless-python-requirements

functions:
  main:
    handler: main.handler
    runtime: nodejs14.x
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
  pdf_processor:
    handler: pollen_collector/pdf_processor/pollen_pdf_processor.handler
    runtime: python3.9
    layers:
      - arn:aws:lambda:eu-west-3:764866452798:layer:ghostscript:10
