import {
  Attribute,
  AutoGeneratedHashKey,
  Table,
  RangeKey,
} from '@skypress/nestjs-dynamodb';
import { embed } from '@aws/dynamodb-data-mapper';
import { PollenCategoryType } from '../pollen-collector/data';

export class PollenGrain {
  @Attribute()
  count: number;
  @Attribute()
  units: string;
}

export class MetricEntryValue {
  @Attribute()
  type: PollenCategoryType;
  @Attribute({ memberType: embed(PollenGrain) })
  polllenGrains: PollenGrain;
}

export class MetricEntry {
  @Attribute()
  lastUpdated: string;

  @Attribute({ memberType: embed(MetricEntryValue) })
  value: MetricEntryValue;
}

@Table('pollen_metrics')
export class PollenMetricsSchema {
  @AutoGeneratedHashKey()
  id: string;

  @RangeKey({ defaultProvider: () => new Date() })
  lastUpdated: Date;

  @Attribute({ memberType: embed(MetricEntry) })
  entries: MetricEntry[];
}
